# CPC Codes
CPC_CODES = {"A": "HUMAN NECESSITIES",
             "B": "PERFORMING OPERATIONS; TRANSPORTING",
             "C": "CHEMISTRY; METALLURGY",
             "D": "TEXTILES; PAPER",
             "E": "FIXED CONSTRUCTIONS",
             "F": "MECHANICAL ENGINEERING; LIGHTING; HEATING; WEAPONS; BLASTING",
             "G": "PHYSICS",
             "H": "ELECTRICITY",
             "Y": "GENERAL TAGGING OF NEW TECHNOLOGICAL DEVELOPMENTS; GENERAL TAGGING OF CROSS-SECTIONAL TECHNOLOGIES SPANNING OVER SEVERAL SECTIONS OF THE IPC; TECHNICAL SUBJECTS COVERED BY FORMER USPC CROSS-REFERENCE ART COLLECTIONS [XRACs] AND DIGESTS"}
